// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWclevjOnc-O58Z9ZfFdA5Pp749sS_s_M',
    appId: '1:301836480927:web:ef585c0570637a17c44daa',
    messagingSenderId: '301836480927',
    projectId: 'floodchonburi',
    authDomain: 'floodchonburi.firebaseapp.com',
    storageBucket: 'floodchonburi.firebasestorage.app',
    measurementId: 'G-Z0GTCS20NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7A5jPGyQHRIWdsJqKE8h0OmfPTNEwH0k',
    appId: '1:301836480927:android:b0334ddf5a391224c44daa',
    messagingSenderId: '301836480927',
    projectId: 'floodchonburi',
    storageBucket: 'floodchonburi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTlsinVNSHNpftLZZX0PU1mvNZco0g9z4',
    appId: '1:301836480927:ios:3fba12ed8d473700c44daa',
    messagingSenderId: '301836480927',
    projectId: 'floodchonburi',
    storageBucket: 'floodchonburi.firebasestorage.app',
    androidClientId: '301836480927-jlurrbs0ifcems4aha8pon2md74lgeb7.apps.googleusercontent.com',
    iosClientId: '301836480927-bbggaha4ksqhvq7fasdj2l69nv3ovnfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.floodAlertChonburi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTlsinVNSHNpftLZZX0PU1mvNZco0g9z4',
    appId: '1:301836480927:ios:3fba12ed8d473700c44daa',
    messagingSenderId: '301836480927',
    projectId: 'floodchonburi',
    storageBucket: 'floodchonburi.firebasestorage.app',
    androidClientId: '301836480927-jlurrbs0ifcems4aha8pon2md74lgeb7.apps.googleusercontent.com',
    iosClientId: '301836480927-bbggaha4ksqhvq7fasdj2l69nv3ovnfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.floodAlertChonburi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWclevjOnc-O58Z9ZfFdA5Pp749sS_s_M',
    appId: '1:301836480927:web:3f7b9b3a285392a0c44daa',
    messagingSenderId: '301836480927',
    projectId: 'floodchonburi',
    authDomain: 'floodchonburi.firebaseapp.com',
    storageBucket: 'floodchonburi.firebasestorage.app',
    measurementId: 'G-8DCTG99F0V',
  );

}